# -*- coding: utf-8 -*-
"""NHM_Specimen_Data_Access_via_GBIF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12aMwJT6BDsnO64n5ozOgDLRIim78qyLN
"""

pip install requests

pip install pandas

import requests
import pandas as pd

GBIF_OCCURRENCE_SEARCH = "https://api.gbif.org/v1/occurrence/search"

# Explicit NHM identifier
NHM_INSTITUTION_CODE = "NHMUK"


def search_nhm_occurrences(
    scientific_name=None,
    country=None,
    year=None,
    limit=20,
    offset=0
):
    """
    Search GBIF occurrence records restricted to
    Natural History Museum (NHM), London specimens.

    NHM scoping is enforced using:
    - institutionCode = NHMUK

    This ensures that only records held by NHM are returned,
    even if they are published across multiple GBIF datasets.
    """

    params = {
        "limit": limit,
        "offset": offset,

        # Explicit NHM-only filter
        "institutionCode": NHM_INSTITUTION_CODE
    }

    if scientific_name:
        params["scientificName"] = scientific_name
    if country:
        params["country"] = country
    if year:
        params["year"] = year  # e.g. "1800,1950"

    response = requests.get(GBIF_OCCURRENCE_SEARCH, params=params)
    response.raise_for_status()

    return response.json()

data = search_nhm_occurrences(
    scientific_name="Quercus robur",
    country="GB",
    year="1800,1950",
    limit=10
)

df = pd.DataFrame(data["results"])

df











